sudo: false
language: node_js
node_js:
  - "6"
  - "8"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_install:
  - npm install -g bob coveralls --loglevel error
script:
  - DEBUG=canihaz bob build
after_success:
  - cat .bob/coverage/buster-istanbul/lcov.info | coveralls
